Add warning about locally closed resources being undefined behavior
async-interop/event-loop pull request #109
Opened 2016-10-24 15:10 UTC by kelunik

Also makes Loop docs consistent with Driver. Resolves #106.

2016-10-24 15:15 UTC, bwoebi requested changes

2016-10-24 15:15 UTC, bwoebi commented on src/Loop.php
> +     * watcher when closing the resource locally. Drivers might choose to notify the user in a debug mode if there are
s/might choose to notify the user in a debug mode/may choose to notify the user

There's no need for talking about a debug mode - that's an implementation detail unrelated to the specification here.

2016-10-24 15:17 UTC, kelunik commented on src/Loop.php
> +     * watcher when closing the resource locally. Drivers might choose to notify the user in a debug mode if there are
There's no _need_, but just a hint.

2016-10-24 15:20 UTC, bwoebi commented on src/Loop.php
> +     * watcher when closing the resource locally. Drivers might choose to notify the user in a debug mode if there are
The emphasis is on removing "in a debug mode". Just keep it out, it has no business here.

2016-10-24 15:21 UTC, bwoebi approved these changes

2016-10-25 07:29 UTC, WyriHaximus approved these changes
:+1:

2016-10-25 10:21 UTC, kelunik commented on src/Loop/Driver.php
> +     * watcher when closing the resource locally. Drivers may choose to notify the user if there are watchers on invalid
Maybe we should write `MAY`

2016-10-25 15:38 UTC, kelunik commented
Forgot to copy `defer`, `delay`, `repeat` from `Driver` to `Loop`. Also replaced `may` with `MAY` and rebased onto `master`.

2016-10-25 16:27 UTC, merged

2016-10-25 18:23 UTC, bwoebi commented
Feel free - would be consistent with the other text.

Bob Weinand (iPhone)

> Am 25.10.2016 um 12:21 schrieb Niklas Keller <notifications@github.com>:
> 
> @kelunik commented on this pull request.
> 
> In src/Loop/Driver.php:
> 
> > @@ -81,9 +81,9 @@
>       * Execute a callback when a stream resource becomes readable or is closed for reading.
>       *
>       * Warning: Closing resources locally, e.g. with `fclose`, might not invoke the callback. Be sure to `cancel` the
> -     * watcher when closing the resource locally. Drivers might choose to notify the user in a debug mode if there are
> -     * watchers on invalid resources, but are not required to, due to the high performance impact. Watchers on closed
> -     * resources are therefore undefined behavior.
> +     * watcher when closing the resource locally. Drivers may choose to notify the user if there are watchers on invalid
> Maybe we should write MAY
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-10-25 19:02 UTC, kelunik commented
That's a bit late.