Define 'tick'
async-interop/event-loop pull request #141
Opened 2017-01-13 14:14 UTC by kelunik

2017-01-14 11:44 UTC, bwoebi commented on src/Loop/Driver.php
> +     *  1. Activate watchers created / enabled in the last tick / before `run`.
With \`run\` you are referencing the method? Please suffix `()` then to make this more obvious.

2017-01-14 11:45 UTC, bwoebi commented on src/Loop/Driver.php
> +     *  4. Execute actionable stream watchers, each only once per tick.
Uh, there is no order guarantee between timers and stream watchers. Merge these two into a single step.

2017-01-20 15:20 UTC, kelunik commented on src/Loop/Driver.php
> +     *  1. Activate watchers created / enabled in the last tick / before `run`.
Fixed.

2017-01-20 15:20 UTC, kelunik commented on src/Loop/Driver.php
> +     *  4. Execute actionable stream watchers, each only once per tick.
Fixed, once per tick should be fine?

2017-01-20 15:27 UTC, bwoebi commented on src/Loop/Driver.php
> +     *  4. Execute actionable stream watchers, each only once per tick.
yes, that's fine.

2017-01-20 15:27 UTC, bwoebi approved these changes

2017-01-22 15:47 UTC, trowski requested changes

2017-01-22 15:47 UTC, trowski commented on src/Loop/Driver.php
> +     *  3. Execute all due timer and actionable stream callbacks, each only once per tick.
Can signals be executed at any time or should they be included in this step? All current implementations execute pending signals only in this step, but should that be part of the spec?

2017-01-22 15:50 UTC, bwoebi commented on src/Loop/Driver.php
> +     *  3. Execute all due timer and actionable stream callbacks, each only once per tick.
Yes, they should. Missed that.

2017-01-22 16:09 UTC, kelunik commented on src/Loop/Driver.php
> +     *  3. Execute all due timer and actionable stream callbacks, each only once per tick.
Changed.

2017-01-22 17:27 UTC, trowski approved these changes

2017-01-28 21:35 UTC, merged